name: Deploy Pipeline
parameters:
- name: action
  displayName: Action to perform, such as deploy or setup users on the bastion
  type: string
  values:
    - Deploy
   
trigger: none

jobs:
- ${{ if eq(parameters.action, 'Deploy') }}:
  - job: deploy
    # The pool name determines the target environment, referencing a self-hosted agent
    pool:
      name: $(region)-$(environment)

steps:
- bash: |
   #! /bin/bash
   
   sudo yum update -y
       sudo amazon-linux-extras install -y  php7.2 httpd
       sudo systemctl start httpd
       sudo systemctl enable httpd
       sudo systemctl is-enabled httpd
    
       # Set permissions
       sudo usermod -a -G apache ec2-user
       sudo chown -R ec2-user:apache /var/www
       sudo chmod 2775 /var/www && find /var/www -type d -exec sudo chmod 2775 {} \;
       find /var/www -type f -exec sudo chmod 0664 {} \;
       echo " Creating php package"
       echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php 
       rm /var/www/html/phpinfo.php
       sudo yum install php-mbstring php-xml -y
       sudo systemctl restart httpd
       sudo systemctl restart php-fpm
       cd /var/www/html
       wget https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz
       mkdir phpMyAdmin && tar -xvzf phpMyAdmin-latest-all-languages.tar.gz -C phpMyAdmin --strip-components 1
       rm phpMyAdmin-latest-all-languages.tar.gz